version: "3.7"

services: 
  barter_energy_api:
    build: 
      dockerfile: docker/local/dockerfile
    ports: 
      - 9229:9229  
    volumes: 
      - ../../dist:/opt/barter_energy/contact-book-api/dist
      - ../../src:/opt/barter_energy/contact-book-api/src
      - ../../node_modules:/opt/barter_energy/contact-book-api/node_modules
    networks: 
      - barter_energy_network_database
    environment: 
      DATABASE_HOST: barter_energy_database
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_COLLECTION: $DATABASE_COLLECTION
      JWT_SECRET: $JWT_SECRET
  barter_energy_database:
    container_name: barter_energy_database
    build: 
      context: ../..
      dockerfile: docker/database/mysql/dockerfile
    ports: 
      - 3306:$DATABASE_PORT
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_COLLECTION
    networks:
      - barter_energy_network_database
    
networks: 
  barter_energy_network_database: 
    driver: bridge